name: PR Validation
on:
  pull_request:
    branches:
      - develop
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install htmlhint stylelint
      - name: Run HTML lint
        run: npx htmlhint "src/**/*.html"
      - name: Run CSS lint
        run: npx stylelint "styles/**/*.css"

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install parcel
      - name: Build static site
        run: npx parcel build src/index.html
